name: NAER
description: A Tool to Randomize Enemies.
version: 2.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
dependencies:
  archive: ^3.3.6
  args: ^2.4.2
  crclib: ^3.0.0
  csv: ^5.1.1
  euc: ^1.0.6+8
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl: ^0.19.0
  open_file: ^3.3.2
  path: ^1.8.3
  path_provider: ^2.1.1

  uuid: ^4.2.2
  xml: ^6.2.2



flutter:
  assets:
    - assets/images/
    - assets/logomyy.png
    - assets/NaerIcon.png
    - assets/1234.png
    - assets/enemies_ingame/
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf