name: NAER
description: A Tool to Randomize Enemies.
version: 2.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
dependencies:
  archive: ^3.3.6
  args: ^2.4.2
  crclib: ^3.0.0
  csv: ^6.0.0
  euc: ^1.0.6+8
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  open_file: ^3.3.2
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_lints: ^3.0.1
  uuid: ^4.2.2
  xml: ^6.2.2
  tuple: ^2.0.2
  desktop_drop: ^0.4.4
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  crypto: ^3.0.3
  intl: ^0.19.0
  url_launcher: ^6.0.20
  window_manager: ^0.3.8
  bitsdojo_window: ^0.1.6





flutter:
  assets:
    - assets/nier_image_folders/nier_enemy_images/
    - assets/nier_image_folders/nier_boss_images/
    - assets/nier_image_folders/nier_enemies_ingame_images/
    - assets/naer_icons/icon.png
    - assets/naer_backgrounds/error_background.png
    - assets/naer_backgrounds/naer_background.png
    - assets/mods/
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf