name: NAER
description: A Tool to Randomize Enemies.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
dependencies:
  animated_icon_button: ^1.0.2
  archive: ^3.3.6
  args: ^2.4.0
  crclib: ^3.0.0
  euc: ^1.0.6+8
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_command: ^5.0.0+17
  flutter_linkify: ^6.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.18.1
  open_file: ^3.3.2
  path: ^1.8.3
  path_provider: ^2.1.1
  test: ^1.24.9
  tuple: ^2.0.1
  url_launcher: ^6.2.1
  uuid: ^3.0.7
  xml: ^6.2.2
  rename_app: ^1.3.1
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  vector_math: ^2.1.4

flutter:
  assets:
    - assets/images/
    - assets/logomyy.png
    - assets/NaerIcon.png
    - assets/1234.png
    - assets/enemies_ingame/
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf