name: NAER
description: A Tool to Randomize Enemies.
version: 3.5.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0
dependencies:
  archive: ^3.3.6
  args: ^2.4.2
  crclib: ^3.0.0
  euc: ^1.0.6+8
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter

  path: ^1.8.3
  path_provider: ^2.1.1
  xml: ^6.2.2
  tuple: ^2.0.2
  desktop_drop: ^0.4.4
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  crypto: ^3.0.3
  intl: ^0.19.0
  stack_trace: ^1.11.1
  automato_theme:
    git:
      url: https://github.com/Vluurie/automato_theme.git
      ref: main 
  flutter_riverpod: ^2.5.1
  isolate: ^2.1.1
  ffi: ^2.1.2
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  window_manager: ^0.4.0
  http: ^1.2.2
  win32: ^5.5.3
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  lottie: ^3.1.2
  tutorial_coach_mark: ^1.2.11






flutter:
  assets:
    - assets/nier_image_folders/nier_enemy_images/
    - assets/nier_image_folders/nier_boss_images/
    - assets/nier_image_folders/nier_enemies_ingame_images/
    - assets/naer_icons/icon.png
    - assets/naer_backgrounds/error_background.png
    - assets/naer_backgrounds/naer_background.png
    - assets/animations/
    - assets/setups_images/
    - assets/videos/
    - assets/mods/
    - .env
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf